### PR TITLE
Add KB DataForm Dynamically Update PickerEditor Data Source

### PR DESCRIPTION
**Pull request by LanceMcCarthy**

### CODE REVIEW

**Comment by StefanNenchev** [comment]
Hi Lance,

This does not seem to work in iOS and UWP, is it intended? Should we consider another approach?

**Comment by StefanNenchev** [comment]
Calling Reload on the DataForm is not sufficient in iOS and UWP.
Seems like clearing the "Source" of the RadDataForm does the trick. For Example:

dataForm.Source = null;
dataForm.Reload();
dataForm.Source = this.CurrentStudent;

You can check the example in TID: 1153425

**Comment by LanceMcCarthy** [comment]
@StefanNenchev Sorry, I didn't see notification for this thread. I'll test and update the KB tomorrow

**Comment by LanceMcCarthy** [comment]
@StefanNenchev Changes made.

**Pull request merged**
